### ISSUE TITLE
ES2015 is not correct

### ISSUE THREAD

**Issue by jussi-kalliokoski** [stoeffel/curry-this#11]
The bind syntax is not part of ES2015 and might not make it to ES2016 either, I'd maybe change the reference in https://github.com/stoeffel/chickencurry/commit/4ba7036359d4b550b11039324f22940ef5bd4ca5#diff-04c6e90faac2675aa89e2176d2eec7d8R32 to something like "future JS feature in proposal stage". :)

Nice, btw, saves me from adding a `curry` to Trine! Unless I want curry to do something different. :D That said, I personally find it a bit weird that it's mixing partial application and currying, but that's just me. :P

**Comment by stoeffel** [comment]
> The bind syntax is not part of ES2015 and might not make it to ES2016 either, I'd maybe change the reference in 4ba7036#diff-04c6e90faac2675aa89e2176d2eec7d8R32 to something like "future JS feature in proposal stage". :)

Thanks, for the hint. Will fix that.

> Nice, btw, saves me from adding a curry to Trine!

:smile: @tomekwi and I are working to make the api even simpler. With the next version we will also rename the project to `curry-this`. As soon as it's ready it would be cool to get your feedback. 
I think that we should also link to `trine` and mention that the two work great together.

**Comment by tomekwi** [comment]
@jussi-kalliokoski it’s an honour seeing you around here!

The reason we’re mixing currying and partial application is simplicity of the API. In a world where the arity of a function is implicit and there many [confilicting community conventions](https://github.com/mattdesl/module-best-practices/issues/7) you end up with [crazy complicated APIs](https://github.com/dominictarr/curry/tree/3f1ca1454368a6561739843ae57e08d6b62d7086#curryto) for both things.

And since both currying and partial application are in fact two means to achieve a similar goal, we decided to marry them into one simple API. Have you seen the [the draft at the v3 branch](https://github.com/stoeffel/chickencurry/blob/357db73d8eaef0502954ecfbe9711b5782790129/README.md)?

**Comment by jussi-kalliokoski** [comment]
@stoeffel 

> As soon as it's ready it would be cool to get your feedback.

Will be happy to provide!

> I think that we should also link to trine and mention that the two work great together.

Yup! Once you release I'll also add a new section to Trine about libraries that play well together with it. :)

@tomekwi 

> it’s an honor seeing you around here!

The honor is all yours (meaning the both of you) for creating this. ^.^

> The reason we’re mixing currying and partial application is simplicity of the API.
> ...
> And since both currying and partial application are in fact two means to achieve a similar goal, we decided to marry them into one simple API.

That makes sense - have been thinking the same myself a couple of times. I think it's just the old API that confuses me. :) Keep up the good work!

**Comment by stoeffel** [comment]
@jussi-kalliokoski fyi. we did release v3. thx for your input.
