### ISSUE TITLE
How do we handle implicit arity?

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/curry-this#17]
We want the API to be explicit and easy to use. I would do it like this:

```js
const f = (a, b, c) => …;  // f.length === 3
```

API call          | Implied length
------------------|------------------
`f::curry()` | 3
`f::curry(1)` | 3
`f::curry(_, 1)` | 3
`f::curry(_, 1, 2)` | 3
`f::curry(_, 1, 2, _)` | 4
`f::curry(_, _, _, _, _)` | 5
`f::curry(_, _, _, _, _, _)` | 6

So, summing up, `f::curry(...args)` assumes the arity of `f` to be `Math.max(f.length, args.length)`.

In any case `::curry` returns a Haskell-like fixed-arity function with auto currying.

Does that [convince you](https://github.com/stoeffel/chickencurry/issues/11#issue-97704456), @jussi-kalliokoski? Perhaps the name `curry` is wrong?

**Comment by stoeffel** [comment]
> We want the API to be explicit and easy to use. I would do it like this:

Totally agree.

> Perhaps the name curry is wrong?

I would still go with `curry`.

**Comment by tomekwi** [comment]
And one more table:

API call          | `g.length`
------------------|----
`g = f::curry()` | 3
`g = f::curry(1)` | 2
`g = f::curry(_, 1)` | 2
`g = f::curry(_, 1, 2)` | 1
`g = f::curry(_, 1, 2, _)` | 2
`g = f::curry(_, _, _, _, _)` | 5
`g = f::curry(_, _, _, _, _, _)` | 6

**Comment by jussi-kalliokoski** [comment]
If implied length is the length of `f`, the first table looks right.

Are you going to overwrite the length of the resulting function?

The latter table also looks right to me as well - there's multiple choices in between implicit vs explicit here and I think the one proposed by that table is a good balance. On the other hand, one option is to ignore the function's length if there are placeholders. That would allow suppressing parameters, like Trine's `partial`:

```javascript
function f (a, b, c) { console.log(a, b, c); }
g = f::curry(_, 1);
g.length; // 1
g(2, 3); // logs 2 1
```

not sure how useful that is for "homemade" functions but 3rd party (including std lib) functions tend to have a ton of mostly useless arguments and overloads that always sneak out to make a bug in a hard to find place. Of course, you can partially apply `undefined` or `null` to those slots, but sadly often the overloads are based on `arguments.length` instead of a null check.

**Comment by tomekwi** [comment]
> If implied length is the length of f, the first table looks right.

Yup, that’s the case. I should have made it explicit.

> one option is to ignore the function's length if there are placeholders. That would allow suppressing parameters […]. Often the overloads are based on arguments.length instead of a null check.

That’s a good point. The more I think about it, the more sense it makes to me. Thanks!

`([encoding], path, [options], [anotherFancyFeature], callback)` – we really need to handle these pesky overloads. I see two options:

* `f::curry(_, 2)(1) === f(1, 2)`
* `f::curry(_, 2, undefined)(1) === f(1, 2)`

– and I guess the first one by @jussi-kalliokoski is the way to go. Least astonishment.

**Comment by stoeffel** [comment]
> one option is to ignore the function's length if there are placeholders.

SGTM. We need to make that clear in the readme.

**Comment by stoeffel** [comment]
Check out https://github.com/stoeffel/chickencurry/commit/fc9131fbd58b7fb7028e96f15d0b0a8b136eec45. Now `curry` ignores the function's length if a user passes `placeholders` in the initial call (see [here](https://github.com/stoeffel/chickencurry/commit/fc9131fbd58b7fb7028e96f15d0b0a8b136eec45#diff-46123e11db327a22161195cee8dacd52R74) and [here](https://github.com/stoeffel/chickencurry/commit/fc9131fbd58b7fb7028e96f15d0b0a8b136eec45#diff-b79a372cd9354638ec6f6356edcc6b5dR65)).
